// Display names are intentionally preserved from the supplied curriculum.
export const academicCurriculum = [
  [
    "Electronics",
    "Mathematics 1",
    "Technical Report Writing",
    "Human Rights",
    "Discrete Math",
    "Introduction to Computers",
  ],
  [
    "Probability and Statistics-1",
    "Creative and Scientific Thinking",
    "Mathematics-2",
    "Micro Economics",
    "Logic Design",
    "Programming Language",
  ],
  [
    "Object Oriented Programming",
    "Introduction to Database systems",
    "Mathematics-3",
    "Computer Networks Technology",
    "Probability and Statistics-2",
    "Introduction to Software Engineering",
  ],
  [
    "Introduction to Operation Research",
    "Data Structure",
    "Machine Learning Fundamentals",
    "Web Technology",
    "Entrepreneurship",
    "Networking Fundamentals lab",
  ],
  [
    "Network Routing and Switching-Lab",
    "Artificial intelligence",
    "Operating Systems",
    "Digital Signal Processing",
    "Computer Organization",
    "Algorithms analysis and Design",
  ],
  [
    "Pattern Recognition",
    "Information Computer Networks Security",
    "Natural Language Processing",
    "Advanced Software Engineering",
    "Microcontroller",
    "Ethical Hacking-lab",
  ],
  [
    "Selected labs in Software Engineering",
    "Embedded Systems",
    "Computer Graphics",
    "Advanced Computer Networks",
    "Project (1)",
    "Communication Technology",
  ],
  [
    "Cloud Computing Networking",
    "Semantic Web and ontology",
    "Wireless and Mobile Networks",
    "Fundamental of Management",
    "Project (2)",
    "Selected labs in AI",
  ],
] as const;
